/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

/**
 *
 * @author KATHERIN
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Contenedor = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu11 = new javax.swing.JMenu();
        Menu_Almacen = new javax.swing.JMenu();
        SubMenu_Producto = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        SubMenu_Ventas = new javax.swing.JMenu();
        SubMenu_Clientes = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        SubMenu_VentasRealizadas = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        SubMenu_Empleado = new javax.swing.JMenu();
        SubMenu_TipoUsuario = new javax.swing.JMenu();
        jMenu10 = new javax.swing.JMenu();
        SubMenu_CambiarContraseña = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout ContenedorLayout = new javax.swing.GroupLayout(Contenedor);
        Contenedor.setLayout(ContenedorLayout);
        ContenedorLayout.setHorizontalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 689, Short.MAX_VALUE)
        );
        ContenedorLayout.setVerticalGroup(
            ContenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 389, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 0, 153));
        jMenuBar1.setBorder(null);

        jMenu11.setText("Usuario");
        jMenuBar1.add(jMenu11);

        Menu_Almacen.setText("Almacen");

        SubMenu_Producto.setText("Producto");
        Menu_Almacen.add(SubMenu_Producto);

        jMenuBar1.add(Menu_Almacen);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ventas.png"))); // NOI18N
        jMenu4.setText("Ventas");

        SubMenu_Ventas.setText("Ventas");
        jMenu4.add(SubMenu_Ventas);

        SubMenu_Clientes.setText("Cliente");
        jMenu4.add(SubMenu_Clientes);

        jMenuBar1.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reporte.png"))); // NOI18N
        jMenu5.setText("Consultas");

        SubMenu_VentasRealizadas.setText("Ventas Realizadas");
        jMenu5.add(SubMenu_VentasRealizadas);

        jMenuBar1.add(jMenu5);

        jMenu8.setText("Mantenimiento");
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });

        SubMenu_Empleado.setText("Empleado");
        SubMenu_Empleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubMenu_EmpleadoActionPerformed(evt);
            }
        });
        jMenu8.add(SubMenu_Empleado);

        SubMenu_TipoUsuario.setText("Tipo de Usuario");
        jMenu8.add(SubMenu_TipoUsuario);

        jMenuBar1.add(jMenu8);

        jMenu10.setText("Herramientas");

        SubMenu_CambiarContraseña.setText("Cambiar Contraseña");
        jMenu10.add(SubMenu_CambiarContraseña);

        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Contenedor)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SubMenu_EmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubMenu_EmpleadoActionPerformed
        // TODO add your handling code here:
        frmVenta empleado = new frmVenta();
        Contenedor.add(empleado);
        empleado.show();
        
    }//GEN-LAST:event_SubMenu_EmpleadoActionPerformed

    private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Contenedor;
    private javax.swing.JMenu Menu_Almacen;
    private javax.swing.JMenu SubMenu_CambiarContraseña;
    private javax.swing.JMenu SubMenu_Clientes;
    private javax.swing.JMenu SubMenu_Empleado;
    private javax.swing.JMenu SubMenu_Producto;
    private javax.swing.JMenu SubMenu_TipoUsuario;
    private javax.swing.JMenu SubMenu_Ventas;
    private javax.swing.JMenu SubMenu_VentasRealizadas;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu11;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
